Add controllers
DenisenkoMax/java-shareit pull request #1
Opened 2022-08-26 10:48 UTC by DenisenkoMax

Спринт 13

2022-08-27 20:59 UTC, kukolev requested changes

2022-08-27 20:59 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>   * // TODO .
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-08-27 20:59 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>   * // TODO .
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-08-27 20:59 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +
Лишняя пустая строка между аннотаций и классом. Выглядит непривычно, лучше удалить.

2022-08-27 20:59 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>   * // TODO .
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-08-27 20:59 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>   * // TODO .
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-08-27 20:59 UTC, kukolev commented on src/main/java/ru/practicum/shareit/requests/ItemRequest.java
>   * // TODO .
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-08-27 20:59 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/User.java
>   * // TODO .
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-08-27 20:59 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserController.java
>   * // TODO .
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-08-27 20:59 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +      validateNoExistEmail(user);
Нарушение требований кодстайла: Не хватает двух пробелов перед « validateNoExistEmail». Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-08-29 05:44 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>   * // TODO .
исправлено

2022-08-29 05:45 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>   * // TODO .
исправлено

2022-08-29 05:45 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +
исправлено

2022-08-29 05:45 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>   * // TODO .
исправлено

2022-08-29 05:45 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>   * // TODO .
исправлено

2022-08-29 05:45 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/requests/ItemRequest.java
>   * // TODO .
исправлено

2022-08-29 05:45 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/user/User.java
>   * // TODO .
исправлено

2022-08-29 05:45 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/user/UserController.java
>   * // TODO .
исправлено

2022-08-29 05:45 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +      validateNoExistEmail(user);
исправлено

2022-08-29 21:08 UTC, kukolev approved these changes

2022-09-08 02:02 UTC, merged