Спринт 14
DenisenkoMax/java-shareit pull request #2
Opened 2022-09-17 19:54 UTC by DenisenkoMax

2022-09-18 18:53 UTC, kukolev requested changes

2022-09-18 18:53 UTC, kukolev commented on pom.xml
> +		<version>2.7.2</version>
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-18 18:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        if (booking != null) {
Этот код можно немного упростить:
Сейчас так:
```
if (!...) {
    // some logic here
} else return null;

```
Проще так:
```
if (...) return null;
// some logic here
```

В моем варианте нет вложенного кода и так код смотрится проще. 
Аналогично рекомендую поправить ниже.

2022-09-18 18:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public int hashCode() {
Текущая реализация фактически означает константный хэшкод. Это плохая практика, т.к. использование такого объекта в качестве ключа в HashMap/HashSet приведет уменьшению скорости доступа по ключу до O(n). Здесь это роли не играет, но вообще это плохая практика. Лучше воспользоваться авто-генерацией методов equals и hashCode в IDEA или написать метод самостоятельно, используя поля класса.

2022-09-18 18:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public int hashCode() {
Текущая реализация фактически означает константный хэшкод. Это плохая практика, т.к. использование такого объекта в качестве ключа в HashMap/HashSet приведет уменьшению скорости доступа по ключу до O(n). Здесь это роли не играет, но вообще это плохая практика. Лучше воспользоваться авто-генерацией методов equals и hashCode в IDEA или написать метод самостоятельно, используя поля класса.

2022-09-18 18:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +        return getClass().hashCode();
Текущая реализация фактически означает константный хэшкод. Это плохая практика, т.к. использование такого объекта в качестве ключа в HashMap/HashSet приведет уменьшению скорости доступа по ключу до O(n). Здесь это роли не играет, но вообще это плохая практика. Лучше воспользоваться авто-генерацией методов equals и hashCode в IDEA или написать метод самостоятельно, используя поля класса.

2022-09-18 18:53 UTC, kukolev commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-18 18:53 UTC, kukolev commented on src/main/shareit.trace.db
> +2022-09-17 19:48:06 jdbc[3]: exception
Этот файл не относится к исходному коду проекта. Все лишние файлы нужно удалить из пул-реквеста.

2022-09-18 18:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/CommentMapper.java
> +        if (commentDto != null) {
Этот код можно немного упростить:
Сейчас так:
```
if (!...) {
    // some logic here
} else return null;

```
Проще так:
```
if (...) return null;
// some logic here
```

В моем варианте нет вложенного кода и так код смотрится проще. 
Аналогично рекомендую поправить ниже.

2022-09-18 18:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +        if (item != null) {
Этот код можно немного упростить:
Сейчас так:
```
if (!...) {
    // some logic here
} else return null;

```
Проще так:
```
if (...) return null;
// some logic here
```

В моем варианте нет вложенного кода и так код смотрится проще. 
Аналогично рекомендую поправить ниже.

2022-09-19 02:25 UTC, DenisenkoMax commented on pom.xml
> +		<version>2.7.2</version>
Исправлено

2022-09-19 02:25 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        if (booking != null) {
Исправлено

2022-09-19 02:27 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public int hashCode() {
Исправлено

2022-09-19 02:27 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public int hashCode() {
Исправлено

2022-09-19 02:27 UTC, DenisenkoMax commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
Исправлено

2022-09-19 02:28 UTC, DenisenkoMax commented on src/main/shareit.trace.db
> +2022-09-17 19:48:06 jdbc[3]: exception
Исправлено

2022-09-19 02:28 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/item/CommentMapper.java
> +        if (commentDto != null) {
Исправлено

2022-09-19 02:29 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +        if (item != null) {
Исправлено

2022-09-19 12:06 UTC, kukolev requested changes

2022-09-19 12:06 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        if (booking != null)
Здесь и в остальных местах исправлено не так, как рекомендовано в замечании. Рекомендовано так:
```
if (booking == null) return null;
return new BookingDtoAnswer(
    booking.getId(),
    booking.getStart(),
    booking.getEnd(),
    ItemMapper.toItemDto(booking.getItem()),
    UserMapper.toUserDtoAnswer(booking.getBooker()),
    booking.getStatus());

```
Этот код проще, т.к. нет лишних отступов, нет скобок и нет else. Предлагаю поправить так.

2022-09-19 12:06 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@EqualsAndHashCode
Эта аннотация тут не нужна, т.к. аннотация `@Data` и так включает в себя `@EqualsAndHashCode`. Аннотацию нужно убрать.

2022-09-19 12:06 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@EqualsAndHashCode
Эта аннотация тут не нужна, т.к. аннотация @Data и так включает в себя @EqualsAndHashCode. Аннотацию нужно убрать.

2022-09-19 12:19 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@EqualsAndHashCode
исправлено

2022-09-19 12:19 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@EqualsAndHashCode
исправлено

2022-09-19 12:20 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        if (booking != null)
исправлено

2022-09-20 08:57 UTC, kukolev approved these changes

2022-09-20 08:57 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        else return new BookingDtoAnswer(
Это мелочь, но все таки здесь else не нужен. Просто без else этот код и так выполнится.

2022-09-27 02:00 UTC, merged