Add item requests
DenisenkoMax/java-shareit pull request #4
Opened 2022-10-11 18:07 UTC by DenisenkoMax

2022-10-12 13:31 UTC, kukolev requested changes

2022-10-12 13:31 UTC, kukolev commented on pom.xml
> +                        <!--						<failOnViolation>true</failOnViolation>-->
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-12 13:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingRepositoryJpaImpl.java
> +        final int start = (int)pageable.getOffset();
Нарушение требований кодстайла: Не хватает пробела после «(int)». Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-10-12 13:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +        return getClass().hashCode();
Текущая реализация фактически означает константный хэшкод. Это плохая практика, т.к. использование такого объекта в качестве ключа в HashMap/HashSet приведет уменьшению скорости доступа по ключу до O(n). Здесь это роли не играет, но вообще это плохая практика. Лучше воспользоваться авто-генерацией методов equals и hashCode в IDEA или написать метод самостоятельно, используя поля класса.

2022-10-12 13:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    public User(Long id, String name, String email, Set<Item> items, Set<ItemRequest> itemRequests, Set<Booking> bookings) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-12 13:31 UTC, kukolev commented on src/test/java/ru/practicum/shareit/bookingTests/BookingReposytoryJpaTest.java
> +        Assertions.assertEquals(booking.getStart(), bookingRepository.findBookingsByUser(user.getId(),
Этот код можно упростить, если сначала загрузить сохраненный объект из БД, а потом просто его проверить:
```
loadedBooking =  bookingRepository.findBookingsByUser(user.getId(), PageRequest.of(0, 10)).getContent().get(0).getStart());
Assertions.assertEquals(booking.getStart(), loadedBooking.getStart());
Assertions.assertEquals(booking.getEnd(), loadedBooking.getEnd());
```

Аналогично нужно поправить и в остальных подобных тестах.

2022-10-13 03:19 UTC, DenisenkoMax commented on pom.xml
> +                        <!--						<failOnViolation>true</failOnViolation>-->
исправлено

2022-10-13 03:21 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/booking/BookingRepositoryJpaImpl.java
> +        final int start = (int)pageable.getOffset();
исправлено

2022-10-13 03:23 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +        return getClass().hashCode();
Исправлено

2022-10-13 03:24 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    public User(Long id, String name, String email, Set<Item> items, Set<ItemRequest> itemRequests, Set<Booking> bookings) {
Исправлено

2022-10-13 04:17 UTC, DenisenkoMax commented on src/test/java/ru/practicum/shareit/bookingTests/BookingReposytoryJpaTest.java
> +        Assertions.assertEquals(booking.getStart(), bookingRepository.findBookingsByUser(user.getId(),
Исправлено

2022-10-13 16:56 UTC, kukolev requested changes

2022-10-13 16:56 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +        return id.hashCode();
Если id будет == null, то здесь будет выброшен NullPointerException. Эту нужно исправить, как вариант с помощью проверки на null.

2022-10-13 16:56 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +        return id.hashCode();
Если id будет == null, то здесь будет выброшен NullPointerException. Эту нужно исправить, как вариант с помощью проверки на null.

2022-10-13 16:56 UTC, kukolev commented on src/test/java/ru/practicum/shareit/itemRequestControllerTests/ItemRequestIntegrationTest.java
> +    public void findUserOwnerItemRequests() throws NotFoundEx, IllegalArgumentEx {
Не исправлено замечание https://github.com/DenisenkoMax/java-shareit/pull/4#discussion_r993463288
Нужно исправить.

2022-10-13 16:56 UTC, kukolev commented on src/test/java/ru/practicum/shareit/itemRequestControllerTests/ItemRequestIntegrationTest.java
> +    public void findAnotherUsersItemRequests() throws NotFoundEx, IllegalArgumentEx {
Не исправлено замечание https://github.com/DenisenkoMax/java-shareit/pull/4#discussion_r993463288
Нужно исправить.

2022-10-13 16:56 UTC, kukolev commented on src/test/java/ru/practicum/shareit/itemRequestControllerTests/ItemRequestServiceTest.java
> +        Assertions.assertEquals(item.hashCode(),item.hashCode());
Нарушение требований кодстайла: Не хватает пробела после «,». Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-10-13 16:56 UTC, kukolev commented on src/test/java/ru/practicum/shareit/itemTests/ItemControllerTest.java
> +    ItemService service;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-14 04:53 UTC, DenisenkoMax commented on src/test/java/ru/practicum/shareit/itemTests/ItemControllerTest.java
> +    ItemService service;
исправлено

2022-10-14 05:00 UTC, DenisenkoMax commented on src/test/java/ru/practicum/shareit/itemRequestControllerTests/ItemRequestIntegrationTest.java
> +    public void findUserOwnerItemRequests() throws NotFoundEx, IllegalArgumentEx {
Исправлено

2022-10-14 05:01 UTC, DenisenkoMax commented on src/test/java/ru/practicum/shareit/itemRequestControllerTests/ItemRequestIntegrationTest.java
> +    public void findAnotherUsersItemRequests() throws NotFoundEx, IllegalArgumentEx {
Исправлено

2022-10-14 05:01 UTC, DenisenkoMax commented on src/test/java/ru/practicum/shareit/itemRequestControllerTests/ItemRequestServiceTest.java
> +        Assertions.assertEquals(item.hashCode(),item.hashCode());
Исправлено

2022-10-14 05:01 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +        return id.hashCode();
Исправлено

2022-10-14 05:01 UTC, DenisenkoMax commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +        return id.hashCode();
Исправлено

2022-10-14 19:29 UTC, kukolev approved these changes

2022-10-18 03:07 UTC, merged